-- 1. Base Customer 360
-- Aggregates basket-level and shopping-day behaviour to one row per household.

CREATE OR REPLACE TABLE CUSTOMER_ANALYTICS.ANALYTICS.CUSTOMER_360 AS

WITH BASKET_TOTALS AS (
    SELECT
        HOUSEHOLD_KEY,
        BASKET_ID,
        SUM(SALES_VALUE) AS BASKET_SALES_VALUE
    FROM CUSTOMER_ANALYTICS.STAGING.STG_TRANSACTIONS
    GROUP BY
        HOUSEHOLD_KEY,
        BASKET_ID
),

BASKET_METRICS AS (
    SELECT
        HOUSEHOLD_KEY,
        COUNT(*) AS TOTAL_BASKETS,
        AVG(BASKET_SALES_VALUE) AS AVG_BASKET_VALUE,
        SUM(BASKET_SALES_VALUE) AS TOTAL_SALES_VALUE
    FROM BASKET_TOTALS
    GROUP BY HOUSEHOLD_KEY
),

SHOPPING_DAYS AS (
    SELECT DISTINCT
        HOUSEHOLD_KEY,
        DAY
    FROM CUSTOMER_ANALYTICS.STAGING.STG_TRANSACTIONS
),

SHOPPING_DAY_GAPS AS (
    SELECT
        HOUSEHOLD_KEY,
        DAY,
        DAY - LAG(DAY) OVER (
            PARTITION BY HOUSEHOLD_KEY
            ORDER BY DAY
        ) AS DAYS_SINCE_PREVIOUS_SHOPPING_DAY
    FROM SHOPPING_DAYS
),

SHOPPING_METRICS AS (
    SELECT
        HOUSEHOLD_KEY,
        COUNT(*) AS TOTAL_SHOPPING_DAYS,
        COUNT(*) / 711.0 * 30 AS SHOPPING_DAYS_PER_30_DAYS,
        MIN(DAY) AS FIRST_OBSERVED_DAY,
        MAX(DAY) AS LAST_OBSERVED_DAY,
        MAX(DAY) - MIN(DAY) AS OBSERVED_ACTIVITY_SPAN_DAYS,
        711 - MAX(DAY) AS RECENCY_DAYS,
        AVG(DAYS_SINCE_PREVIOUS_SHOPPING_DAY)
            AS AVG_DAYS_BETWEEN_SHOPPING_DAYS
    FROM SHOPPING_DAY_GAPS
    GROUP BY HOUSEHOLD_KEY
)

SELECT
    b.HOUSEHOLD_KEY,
    b.TOTAL_BASKETS,
    s.TOTAL_SHOPPING_DAYS,
    s.SHOPPING_DAYS_PER_30_DAYS,
    b.TOTAL_SALES_VALUE,
    b.AVG_BASKET_VALUE,
    s.FIRST_OBSERVED_DAY,
    s.LAST_OBSERVED_DAY,
    s.OBSERVED_ACTIVITY_SPAN_DAYS,
    s.RECENCY_DAYS,
    s.AVG_DAYS_BETWEEN_SHOPPING_DAYS

FROM BASKET_METRICS b

LEFT JOIN SHOPPING_METRICS s
    ON b.HOUSEHOLD_KEY = s.HOUSEHOLD_KEY;


-- 2. Demographic enrichment
-- Adds available household demographic attributes while preserving all customers.



CREATE OR REPLACE TABLE CUSTOMER_ANALYTICS.ANALYTICS.CUSTOMER_360_ENRICHED AS

SELECT
    c.*,

    IFF(h.HOUSEHOLD_KEY IS NOT NULL, TRUE, FALSE) AS HAS_DEMOGRAPHICS,

    h.AGE_DESC,
    h.MARITAL_STATUS,
    h.INCOME_DESC,
    h.INCOME_BAND_ORDER,
    h.HOMEOWNER_DESC,
    h.HH_COMP_DESC,
    h.HOUSEHOLD_SIZE_DESC,
    h.KID_CATEGORY_DESC

FROM CUSTOMER_ANALYTICS.ANALYTICS.CUSTOMER_360 c

LEFT JOIN CUSTOMER_ANALYTICS.STAGING.STG_HOUSEHOLDS h
    ON c.HOUSEHOLD_KEY = h.HOUSEHOLD_KEY;


-- 3. Campaign and redemption enrichment
-- Adds campaign assignment, redemption activity and campaign-response features.

CREATE OR REPLACE TABLE CUSTOMER_ANALYTICS.ANALYTICS.CUSTOMER_360_FINAL AS

WITH CAMPAIGN_METRICS AS (
    SELECT
        HOUSEHOLD_KEY,

        COUNT(DISTINCT CAMPAIGN) AS TOTAL_CAMPAIGNS_ASSIGNED,

        COUNT(DISTINCT CASE
            WHEN CAMPAIGN_TYPE = 'TypeA' THEN CAMPAIGN
        END) AS TYPE_A_CAMPAIGNS_ASSIGNED,

        COUNT(DISTINCT CASE
            WHEN CAMPAIGN_TYPE = 'TypeB' THEN CAMPAIGN
        END) AS TYPE_B_CAMPAIGNS_ASSIGNED,

        COUNT(DISTINCT CASE
            WHEN CAMPAIGN_TYPE = 'TypeC' THEN CAMPAIGN
        END) AS TYPE_C_CAMPAIGNS_ASSIGNED

    FROM CUSTOMER_ANALYTICS.STAGING.STG_CAMPAIGN_HOUSEHOLDS
    GROUP BY HOUSEHOLD_KEY
),

REDEMPTION_METRICS AS (
    SELECT
        HOUSEHOLD_KEY,
        COUNT(*) AS TOTAL_REDEMPTION_EVENTS,
        COUNT(DISTINCT COUPON_UPC) AS UNIQUE_COUPONS_REDEEMED,
        COUNT(DISTINCT CAMPAIGN) AS CAMPAIGNS_WITH_REDEMPTION
    FROM CUSTOMER_ANALYTICS.STAGING.STG_COUPON_REDEMPTIONS
    GROUP BY HOUSEHOLD_KEY
)

SELECT
    c.*,

    IFF(cm.HOUSEHOLD_KEY IS NOT NULL, TRUE, FALSE)
        AS HAS_CAMPAIGN_ASSIGNMENT,

    COALESCE(cm.TOTAL_CAMPAIGNS_ASSIGNED, 0)
        AS TOTAL_CAMPAIGNS_ASSIGNED,

    COALESCE(cm.TYPE_A_CAMPAIGNS_ASSIGNED, 0)
        AS TYPE_A_CAMPAIGNS_ASSIGNED,

    COALESCE(cm.TYPE_B_CAMPAIGNS_ASSIGNED, 0)
        AS TYPE_B_CAMPAIGNS_ASSIGNED,

    COALESCE(cm.TYPE_C_CAMPAIGNS_ASSIGNED, 0)
        AS TYPE_C_CAMPAIGNS_ASSIGNED,

    IFF(rm.HOUSEHOLD_KEY IS NOT NULL, TRUE, FALSE)
        AS HAS_COUPON_REDEMPTION,

    COALESCE(rm.TOTAL_REDEMPTION_EVENTS, 0)
        AS TOTAL_REDEMPTION_EVENTS,

    COALESCE(rm.UNIQUE_COUPONS_REDEEMED, 0)
        AS UNIQUE_COUPONS_REDEEMED,

    COALESCE(rm.CAMPAIGNS_WITH_REDEMPTION, 0)
        AS CAMPAIGNS_WITH_REDEMPTION,

    CASE
        WHEN cm.TOTAL_CAMPAIGNS_ASSIGNED > 0
        THEN COALESCE(rm.CAMPAIGNS_WITH_REDEMPTION, 0)
             / cm.TOTAL_CAMPAIGNS_ASSIGNED::FLOAT
        ELSE NULL
    END AS CAMPAIGN_REDEMPTION_INCIDENCE

FROM CUSTOMER_ANALYTICS.ANALYTICS.CUSTOMER_360_ENRICHED c

LEFT JOIN CAMPAIGN_METRICS cm
    ON c.HOUSEHOLD_KEY = cm.HOUSEHOLD_KEY

LEFT JOIN REDEMPTION_METRICS rm
    ON c.HOUSEHOLD_KEY = rm.HOUSEHOLD_KEY;