-- Campaign performance analysis
-- Calculates assigned households, coupon redeemers, campaign response rate,
-- pre-campaign sales, during-campaign sales and descriptive sales change.


CREATE OR REPLACE TABLE CUSTOMER_ANALYTICS.ANALYTICS.CAMPAIGN_PERFORMANCE AS

WITH ASSIGNMENTS AS (
    SELECT
        CAMPAIGN,
        CAMPAIGN_TYPE,
        COUNT(DISTINCT HOUSEHOLD_KEY) AS ASSIGNED_HOUSEHOLDS
    FROM CUSTOMER_ANALYTICS.STAGING.STG_CAMPAIGN_HOUSEHOLDS
    GROUP BY CAMPAIGN, CAMPAIGN_TYPE
),

REDEMPTIONS AS (
    SELECT
        CAMPAIGN,
        COUNT(DISTINCT HOUSEHOLD_KEY) AS REDEEMING_HOUSEHOLDS,
        COUNT(*) AS TOTAL_REDEMPTION_EVENTS
    FROM CUSTOMER_ANALYTICS.STAGING.STG_COUPON_REDEMPTIONS
    GROUP BY CAMPAIGN
),

CAMPAIGN_WINDOWS AS (
    SELECT
        CAMPAIGN,
        START_DAY,
        END_DAY,
        START_DAY - CAMPAIGN_DURATION_DAYS AS PRE_START_DAY,
        START_DAY - 1 AS PRE_END_DAY
    FROM CUSTOMER_ANALYTICS.STAGING.STG_CAMPAIGNS
),

CAMPAIGN_SALES AS (
    SELECT
        a.CAMPAIGN,

        SUM(CASE
            WHEN t.DAY BETWEEN w.PRE_START_DAY AND w.PRE_END_DAY
            THEN t.SALES_VALUE ELSE 0
        END) AS PRE_CAMPAIGN_SALES,

        SUM(CASE
            WHEN t.DAY BETWEEN w.START_DAY AND w.END_DAY
            THEN t.SALES_VALUE ELSE 0
        END) AS DURING_CAMPAIGN_SALES

    FROM CUSTOMER_ANALYTICS.STAGING.STG_CAMPAIGN_HOUSEHOLDS a

    JOIN CAMPAIGN_WINDOWS w
        ON a.CAMPAIGN = w.CAMPAIGN

    LEFT JOIN CUSTOMER_ANALYTICS.STAGING.STG_TRANSACTIONS t
        ON a.HOUSEHOLD_KEY = t.HOUSEHOLD_KEY
       AND t.DAY BETWEEN w.PRE_START_DAY AND w.END_DAY

    GROUP BY a.CAMPAIGN
)

SELECT
    a.CAMPAIGN,
    a.CAMPAIGN_TYPE,
    a.ASSIGNED_HOUSEHOLDS,

    COALESCE(r.REDEEMING_HOUSEHOLDS, 0)
        AS REDEEMING_HOUSEHOLDS,

    COALESCE(r.TOTAL_REDEMPTION_EVENTS, 0)
        AS TOTAL_REDEMPTION_EVENTS,

    ROUND(
        COALESCE(r.REDEEMING_HOUSEHOLDS, 0)
        * 100.0 / a.ASSIGNED_HOUSEHOLDS,
        1
    ) AS RESPONSE_RATE_PCT,

    ROUND(s.PRE_CAMPAIGN_SALES, 2)
        AS PRE_CAMPAIGN_SALES,

    ROUND(s.DURING_CAMPAIGN_SALES, 2)
        AS DURING_CAMPAIGN_SALES,

    ROUND(
        (s.DURING_CAMPAIGN_SALES - s.PRE_CAMPAIGN_SALES)
        * 100.0
        / NULLIF(s.PRE_CAMPAIGN_SALES, 0),
        1
    ) AS SALES_CHANGE_PCT

FROM ASSIGNMENTS a

LEFT JOIN REDEMPTIONS r
    ON a.CAMPAIGN = r.CAMPAIGN

JOIN CAMPAIGN_SALES s
    ON a.CAMPAIGN = s.CAMPAIGN;