-- Market basket analysis
-- Identifies frequently co-purchased commodity pairs and calculates
-- support, directional confidence and lift for cross-sell analysis.

CREATE OR REPLACE TABLE CUSTOMER_ANALYTICS.ANALYTICS.MARKET_BASKET_PAIRS AS

WITH BASKET_COMMODITIES AS (
    SELECT DISTINCT
        t.BASKET_ID,
        p.COMMODITY_REPORTING
    FROM CUSTOMER_ANALYTICS.STAGING.STG_TRANSACTIONS t
    JOIN CUSTOMER_ANALYTICS.STAGING.STG_PRODUCTS p
        ON t.PRODUCT_ID = p.PRODUCT_ID
    WHERE t.SALES_VALUE > 0
      AND t.QUANTITY > 0
      AND p.COMMODITY_REPORTING IS NOT NULL
      AND p.COMMODITY_REPORTING NOT IN (
          'UNKNOWN',
          'COUPON/MISC ITEMS'
      )
),

TOTAL_BASKETS AS (
    SELECT COUNT(DISTINCT BASKET_ID) AS TOTAL_BASKETS
    FROM BASKET_COMMODITIES
),

CATEGORY_COUNTS AS (
    SELECT
        COMMODITY_REPORTING,
        COUNT(DISTINCT BASKET_ID) AS CATEGORY_BASKETS
    FROM BASKET_COMMODITIES
    GROUP BY COMMODITY_REPORTING
),

PAIR_COUNTS AS (
    SELECT
        a.COMMODITY_REPORTING AS CATEGORY_A,
        b.COMMODITY_REPORTING AS CATEGORY_B,
        COUNT(DISTINCT a.BASKET_ID) AS BASKETS_TOGETHER
    FROM BASKET_COMMODITIES a
    JOIN BASKET_COMMODITIES b
        ON a.BASKET_ID = b.BASKET_ID
       AND a.COMMODITY_REPORTING < b.COMMODITY_REPORTING
    GROUP BY
        a.COMMODITY_REPORTING,
        b.COMMODITY_REPORTING
)

SELECT
    p.CATEGORY_A,
    p.CATEGORY_B,
    p.BASKETS_TOGETHER,

    ROUND(
        p.BASKETS_TOGETHER * 100.0 / t.TOTAL_BASKETS,
        2
    ) AS SUPPORT_PCT,

    ROUND(
        p.BASKETS_TOGETHER * 100.0 / a.CATEGORY_BASKETS,
        1
    ) AS CONFIDENCE_A_TO_B_PCT,

    ROUND(
        p.BASKETS_TOGETHER * 100.0 / b.CATEGORY_BASKETS,
        1
    ) AS CONFIDENCE_B_TO_A_PCT,

    ROUND(
        (p.BASKETS_TOGETHER * t.TOTAL_BASKETS)
        /
        NULLIF(
            a.CATEGORY_BASKETS * b.CATEGORY_BASKETS,
            0
        ),
        2
    ) AS LIFT

FROM PAIR_COUNTS p

JOIN CATEGORY_COUNTS a
    ON p.CATEGORY_A = a.COMMODITY_REPORTING

JOIN CATEGORY_COUNTS b
    ON p.CATEGORY_B = b.COMMODITY_REPORTING

CROSS JOIN TOTAL_BASKETS t

WHERE p.BASKETS_TOGETHER >= 500;